apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sso-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET:           {{ .Values.secrets.SESSION_SECRET | quote }}
  KEYCLOAK_CLIENT_SECRET:   {{ .Values.secrets.KEYCLOAK_CLIENT_SECRET | quote }}
  GLITCHTIP_PROXY_TOKEN:    {{ .Values.secrets.GLITCHTIP_PROXY_TOKEN | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.secrets.DJANGO_SUPERUSER_PASSWORD | quote }}
