{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sso-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sso-proxy.labels" . | nindent 4 }}
{{- end }}
